# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\faceManageWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 357)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.faceDataList = QtWidgets.QListWidget(self.centralwidget)
        self.faceDataList.setMinimumSize(QtCore.QSize(200, 0))
        self.faceDataList.setObjectName("faceDataList")
        self.horizontalLayout.addWidget(self.faceDataList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.con_addLb = QtWidgets.QLabel(self.centralwidget)
        self.con_addLb.setObjectName("con_addLb")
        self.verticalLayout.addWidget(self.con_addLb)
        self.camAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.camAddBtn.setObjectName("camAddBtn")
        self.verticalLayout.addWidget(self.camAddBtn)
        self.fileAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fileAddBtn.setObjectName("fileAddBtn")
        self.verticalLayout.addWidget(self.fileAddBtn)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.con_modLb = QtWidgets.QLabel(self.centralwidget)
        self.con_modLb.setObjectName("con_modLb")
        self.verticalLayout.addWidget(self.con_modLb)
        self.con_modTipLb = QtWidgets.QLabel(self.centralwidget)
        self.con_modTipLb.setObjectName("con_modTipLb")
        self.verticalLayout.addWidget(self.con_modTipLb)
        self.camUpdBtn = QtWidgets.QPushButton(self.centralwidget)
        self.camUpdBtn.setEnabled(False)
        self.camUpdBtn.setObjectName("camUpdBtn")
        self.verticalLayout.addWidget(self.camUpdBtn)
        self.fileUpdBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fileUpdBtn.setEnabled(False)
        self.fileUpdBtn.setObjectName("fileUpdBtn")
        self.verticalLayout.addWidget(self.fileUpdBtn)
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setEnabled(False)
        self.delBtn.setObjectName("delBtn")
        self.verticalLayout.addWidget(self.delBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.refreshBtn = QtWidgets.QPushButton(self.centralwidget)
        self.refreshBtn.setObjectName("refreshBtn")
        self.verticalLayout.addWidget(self.refreshBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.verticalLayout.addWidget(self.cancelBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸管理"))
        self.label.setText(_translate("MainWindow", "人脸库数据"))
        self.con_addLb.setText(_translate("MainWindow", "人脸添加"))
        self.camAddBtn.setText(_translate("MainWindow", "从相机添加人脸"))
        self.fileAddBtn.setText(_translate("MainWindow", "从文件添加人脸"))
        self.con_modLb.setText(_translate("MainWindow", "人脸更改"))
        self.con_modTipLb.setText(_translate("MainWindow", "在列表中选择人物来更改"))
        self.camUpdBtn.setText(_translate("MainWindow", "从相机更新人脸"))
        self.fileUpdBtn.setText(_translate("MainWindow", "从文件更新人脸"))
        self.delBtn.setText(_translate("MainWindow", "删除人脸"))
        self.refreshBtn.setText(_translate("MainWindow", "刷新"))
        self.cancelBtn.setText(_translate("MainWindow", "取消"))
